### ISSUE TITLE
Changes processed but the website refuses to update mostly?

### ISSUE THREAD

**Issue by vsitante** [ryanvilbrandt/comic_git#76]
Hey! So first, thanks for making this kind of comic CMS! We need more out there! I super appreciate that the instructions were not only easy, but clearly written for dumb dumbs like me, haha.

Which is why it sucks to write the second point--which is that...[my website](https://vsitante.github.io/heaven/) just doesn't update changes?

So I followed the instructions up to the ["Editing the Colors and Layout of the Website,"](https://github.com/ryanvilbrandt/comic_git/wiki/Customizing-your-Website) and that's only because after pushing enough changes through Github desktop, I decided to take a look at my website and...nothing had been updated. The sample comic and layout were still in place. The only changes that stuck were the ones I did outside of the program and Github, e.g. changing the banner and deleting the comics and background. Not even the comic info.ini file appears to have changed. The test comic I uploaded appears nowhere, as the archive page still only shows the sample archive page.

I am at a loss as to what's happening, because all my deployments seem okay and I have no errors or actions to take care of listed anywhere on my own repository. [Here's a link to said repository](https://github.com/vsitante/heaven). 

Any help is appreciated. Thank you!

**Comment by ryanvilbrandt** [comment]
Thanks for using comic_git! Glad you're enjoying it so far!

If you go into the Actions tab in your GitHub repo, you can see that the most recent [Auto-build HTML files](https://github.com/vsitante/heaven/actions/runs/9014591615) job has failed. This indicates something went wrong when trying to build your website, so it left the already-deployed website alone.

If you click into that, you can then click the `build (3.8)` link that has a red X next to it. That will take you to the build job logs, and you can see the "Run python build script" step is where the error happened (red X). That should auto-open for you, and it will show you the following error:

```
Traceback (most recent call last):
  File "src/scripts/build_site.py", line 604, in <module>
    main(parse_args())
  File "src/scripts/build_site.py", line 559, in main
    comic_data_dicts = build_and_publish_comic_pages(
  File "src/scripts/build_site.py", line 163, in build_and_publish_comic_pages
    process_comic_images(comic_info, comic_data_dicts)
  File "src/scripts/build_site.py", line 431, in process_comic_images
    process_comic_image(comic_info, comic_data["comic_path"])
  File "src/scripts/build_site.py", line 418, in process_comic_image
    with open(comic_page_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'your_content/comics/height/Page_197.png'
```

This error isn't entirely clear to new users, and I'll work on making it clearer in the future. But this usually means that you have a "Filename" value in one of your `info.ini` files that doesn't have a matching file.

Looking in your `height` comic folder, I can see you have your comic file named `height1.png`. If you update the "Filename" value in the `info.ini` file to match, your website should build properly.

**Comment by ryanvilbrandt** [comment]
In the future, if your website is not building properly, the [Troubleshooting](https://github.com/ryanvilbrandt/comic_git/wiki/Troubleshooting) page on the wiki will provide useful suggestions for tracking down the issue yourself.

**Comment by ryanvilbrandt** [comment]
First off, please let me applaud you for going through the Troubleshooting section before asking for help! 👏 This puts you in the extreme minority of help requests. On a related note, thank you so much for including your repository in the initial help request.

The folders `archive`, `comic`, `infinite_scroll`, etc are ones that are only created by the comic_git script itself and pushed to the master branch, so that they can be published onto GitHub Pages. When the comic_git build script runs, it pulls down all the files in the `working` branch, runs the build logic on that to create all the website's files, and pushes those files to the `master` branch wiping out any existing changes. As such, those folders should never appear on the `working` branch, which is the branch you should be uploading all your changes to.

Looking in [your repository](https://github.com/vsitante/heaven), I can see that the `working` branch doesn't have those folders, which suggests to me that you may have your `master` branch checked out on your local machine and be pushing your changes to that instead of `working`.

![image](https://github.com/ryanvilbrandt/comic_git/assets/5972092/7ef9d7fe-9ba7-461b-948b-cd0caa2f236e)

Looking in the commit history for your `master` branch, I can see there are a number of changes there that aren't in `working`, which supports my hypothesis.

![image](https://github.com/ryanvilbrandt/comic_git/assets/5972092/e8c7bf4f-fc1b-4d97-aa34-83533245a621)

Please doublecheck that you're uploading your changes to your `working` branch.

**Comment by ryanvilbrandt** [comment]
Ah no, that section is correct. It however refers to this setting:

![image](https://github.com/ryanvilbrandt/comic_git/assets/5972092/9a1ccb11-7575-4c5d-aeb8-e2d70ad52946)

I'll update the text in that section to be a little clearer. And I'll add a troubleshooting step to doublecheck that you're pushing to the `working` branch.

**Comment by ryanvilbrandt** [comment]
In your last screenshot, If you click on the `build (3.8)` next to the red X, that will take you to the build logs. There, I can see the following error:

```
Traceback (most recent call last):
  File "src/scripts/build_site.py", line 604, in <module>
    main(parse_args())
  File "src/scripts/build_site.py", line 5[59](https://github.com/vsitante/heaven/actions/runs/9139524669/job/25131905441#step:7:60), in main
    comic_data_dicts = build_and_publish_comic_pages(
  File "src/scripts/build_site.py", line 209, in build_and_publish_comic_pages
    write_html_files(comic_folder, comic_info, comic_data_dicts, global_values)
  File "src/scripts/build_site.py", line 466, in write_html_files
    write_other_pages(comic_folder, comic_info, comic_data_dicts, global_values)
  File "src/scripts/build_site.py", line 492, in write_other_pages
    utils.write_to_template(page["template_name"], html_path, data_dict)
  File "/home/runner/work/heaven/heaven/src/scripts/utils.py", line 97, in write_to_template
    raise TemplateNotFound(f"Template matching '{template_name}' not found")
jinja2.exceptions.TemplateNotFound: Template matching 'substar' not found
```

This is an error indicating that you are asking comic_git to create an extra web page, but didn't provide an HTML file for comic_git to use for that page (note to self to make this error clearer).

First, are you intending to add an extra page to your website? That's what comic_git thinks you want, since you added `substar = SubscribeStar` under the Pages section, so it's looking for an HTML file named `substar` to use to build the page. If that's not what you intend and you just wanted to add a link to your SubscribeStar, you can delete that line from the Pages section and that error should go away.

If you do want to add a page to your website about SubscribeStar, you just need to go to `your_content/themes/default/templates` and add an HTML file named `substar`. You can read more about this process here: https://github.com/ryanvilbrandt/comic_git/wiki/extra-features#adding-new-pages

**Comment by ryanvilbrandt** [comment]
Glad things are working out for you! I'm going to close this issue, but feel free to reach out if you have more problems.
